#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x
set -o pipefail

error_handler() {
   true "\
###########################################################
## chroot script: ERROR detected. Please report this bug! #
###########################################################"

   exit 1
}

## {{ Set up error handler.
if [ "$(type -t errorhandlergeneral)" = "function" ]; then
   ## Function errorhandlergeneral exists (declared in
   ## help-steps/pre). Prefer to use the more feature rich version of the error
   ## handler.
   trap "errorhandlergeneral" ERR
else
   ## Function errorhandlergeneral does not exist. Script
   ## runs standalone outside the build script. Fall back to a simpler error
   ## handler.
   trap "error_handler" ERR
fi
## }}

own_filename="$(basename "$BASH_SOURCE")"
for skip_script in $SKIP_SCRIPTS; do
   if [ "$skip_script" = "$own_filename" ]; then
      true "INFO: Skipping $own_filename, because SKIP_SCRIPTS includes it."
      exit 0
   fi
done
unset skip_script

## Enable apt-cacher-ng proxy.
if [ "$(type -t aptcachemaybeenable)" = "function" ]; then
   aptcachemaybeenable
fi

[ -n "$EMPTY_DIR" ] || EMPTY_DIR="/tmp/empty"

mkdir --parents "$EMPTY_DIR"

## Debugging.
true "UWT_DEV_PASSTHROUGH: $UWT_DEV_PASSTHROUGH"

## Debugging.
export UWT_VERBOSE=1
true "UWT_VERBOSE: UWT_VERBOSE"

## Debugging.
## Override with || true in case not installed.
## This is the case when --no-default-applications is being used.
which torsocks || true
which uwt || true

if [ "$(type -t aptgetgpgvcreatetmp)" = "function" ]; then
   aptgetgpgvcreatetmp
else
   true 'INFO: function aptgetgpgvcreatetmp does not exist.
If "apt-get update" would show "The following signatures were invalid",
this would probably go unnoticed by the error handler of this script,
hence the following apt repository would be silently ignored.'
fi

if [ "$WHONIX_BUILD_APT_GET_UPDATE_WRAPPER_TEMP_BIN" = "" ]; then
   WHONIX_BUILD_APT_GET_UPDATE_WRAPPER_TEMP_BIN="apt-get"
fi

## Update torproject repository upstream package lists, so latest version of Tor, torsocks and obfsproxy gets known.
$WHONIX_BUILD_APT_GET_UPDATE_WRAPPER_TEMP_BIN \
   $apt_get_gpgv_opts \
   $apt_timeout_opts \
   -o Dir::Etc::sourcelist="/etc/apt/sources.list.d/torproject.list" \
   -o Dir::Etc::sourceparts="$EMPTY_DIR" \
   -o APT::Get::List-Cleanup="0" \
   update

## Disable apt-cacher-ng proxy.
unset http_proxy

if [ "$(type -t aptgetgpgvparsetmp)" = "function" ]; then
   aptgetgpgvparsetmp
fi

if [ "$(type -t aptgetgpgvdeletetmp)" = "function" ]; then
   aptgetgpgvdeletetmp
fi

## Explicitly "exit 0", so eventually trapped errors can be ignored.
exit 0
