#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x
set -o pipefail

error_handler() {
   true "\
###########################################################
## chroot script: ERROR detected. Please report this bug! #
###########################################################"

   exit 1
}

## {{ Set up error handler.
if [ "$(type -t error_handler_general)" = "function" ]; then
   ## Function error_handler_general exists (declared in
   ## help-steps/pre). Prefer to use the more feature rich version of the error
   ## handler.
   trap "error_handler_general" ERR
else
   ## Function error_handler_general does not exist. Script
   ## runs standalone outside the build script. Fall back to a simpler error
   ## handler.
   trap "error_handler" ERR
fi
## }}

own_filename="$(basename "$BASH_SOURCE")"
for skip_script in $SKIP_SCRIPTS; do
   if [ "$skip_script" = "$own_filename" ]; then
      true "INFO: Skipping $own_filename, because SKIP_SCRIPTS includes it."
      exit 0
   fi
done
unset skip_script

## Enable apt-cacher-ng proxy.
if [ "$(type -t maybe_enable_apt_cache)" = "function" ]; then
   maybe_enable_apt_cache
fi

mkdir --parents "$EMPTY_DIR"

## Debugging.
true "UWT_DEV_PASSTHROUGH: $UWT_DEV_PASSTHROUGH"

## Debugging.
export UWT_VERBOSE=1
true "UWT_VERBOSE: UWT_VERBOSE"

## Debugging.
## Override with || true in case not installed.
## This is the case when --no-default-applications is being used.
which torsocks || true
which uwt || true

if [ "$(type -t create_tmp_apt_get_gpgv)" = "function" ]; then
   create_tmp_apt_get_gpgv
else
   true 'INFO: function create_tmp_apt_get_gpgv does not exist.
If "apt-get update" would show "The following signatures were invalid",
this would probably go unnoticed by the error handler of this script,
hence the following apt repository would be silently ignored.'
fi

## Update torproject repository upstream package lists, so latest version of Tor, torsocks and obfsproxy gets known.
apt-get \
   $apt_get_gpgv_opts \
   $apt_timeout_opts \
   -o Dir::Etc::sourcelist="/etc/apt/sources.list.d/torproject.list" \
   -o Dir::Etc::sourceparts="$EMPTY_DIR" \
   -o APT::Get::List-Cleanup="0" \
   update

## Disable apt-cacher-ng proxy.
unset http_proxy

if [ "$(type -t parse_tmp_apt_get_gpgv)" = "function" ]; then
   parse_tmp_apt_get_gpgv
fi

if [ "$(type -t delete_tmp_apt_get_gpgv)" = "function" ]; then
   delete_tmp_apt_get_gpgv
fi

## Explicitly "exit 0", so eventually trapped errors can be ignored.
exit 0
